# The URL the site will be built for
title = "Tejas' Blog"
description = "Thoughts and learnings on writing better software"
base_url = "https://tejasbubane.github.io"
# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
theme = "even"
generate_feed = true
taxonomies = [
    {name = "tags", rss = true},
]

[markdown]
highlight_code = true
highlight_theme = "one-dark"
render_emoji = true
external_links_target_blank = true

[extra]
even_title = "Tejas' Blog"
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/setup", name = "Setup"},
    {url = "$BASE_URL/atom.xml", name = "RSS"}
]
even_profile_name = "Tejas Bubane"
even_profile_info = "Ruby | Javascript | Haskell | Î»"
even_add_google_analytics = true
even_gtag_tracking_id = "UA-152407711-1"

twitter = "https://twitter.com/tejasbubane"
github = "https://github.com/tejasbubane"
linkedin = "http://in.linkedin.com/in/tejasbubane"
stackoverflow = "https://stackoverflow.com/users/3507206/tejasbubane"
slidedeck = "https://speakerdeck.com/tejasbubane"
